#pragma config(Sensor, S1,     color,          sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     ultra,          sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatih6cally generated by 'ROBOTC' configuration wizard               !!*//
 
long colorR, colorB, colorG;
 
 
task main()
{
    while(1)
    {
    nMotorEncoder[left] = 0;
    nMotorEncoder[right] = 0;
    getColorRGB(color,colorR,colorG,colorB);
    //first part, before detecting, object
        while(getUSDistance(ultra) > 10){
        getColorRGB(color,colorR,colorG,colorB);
 
        if(colorR > 19)
        {
            displayCenteredBigTextLine(5,"%d",colorG);
            motor[left] = 10;
            motor[right] = -20;
            getColorRGB(color,colorR,colorG,colorB);
        }
 
        if(colorR < 14)
        {
            displayCenteredBigTextLine(5,"%d",colorG);
            motor[left] = -20;
            motor[right] = 10;
            getColorRGB(color,colorR,colorG,colorB);
        }
 
        if(colorR > 13 && colorR < 20)
        {
            displayCenteredBigTextLine(5,"%d",colorG);
            motor[left] = 40;
            motor[right] = 40;
            getColorRGB(color,colorR,colorG,colorB);
        }
    }
    while(getUSDistance(ultra) < 10)
		{
        motor[left] = 0;
        motor[right] = 0;
        playSound(soundBeepBeep);
        sleep(2000);
        playSound(soundBeepBeep);
        sleep(2000);
        getColorRGB(color,colorR,colorG,colorB);
        displayCenteredBigTextLine(5,"%d",colorR);
        displayCenteredBigTextLine(5,"%d",colorG);
        displayCenteredBigTextLine(5,"%d",colorB);
        if(colorG < 19)
        {
        displayCenteredBigTextLine(5, "%s", "BLUE");
        sleep(5000);
        motor[left] = 5;
        motor[right] = 5;
        wait1Msec(1000);
        turnRight(400, degrees, 30);
        turnLeft(400, degrees, 30);
      	}
       	else
        {
            displayCenteredBigTextLine(5, "%s", "GREEN");
            turnRight(180, degrees, 20);
        }
		}
}
}
