#pragma config(Sensor, S1,     color,          sensorEV3_Color)
#pragma config(Sensor, S4,     ultra,          sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
// turn left if it is black
// turn right if it is white
//below 10 go straight
//above 10 slightly left while going forward
//run into white (above 30) then stop sharp turn until black

task main()
{
	while(1){
	while(getColorReflected(color) > 24)
{
	nMotorEncoder[left] = 0;
	nMotorEncoder[right] = 0;
	motor[left] = 50;
	motor[right] = 0;
}
	while(getColorReflected(color) < 16)
	{
	nMotorEncoder[left] = 0;
	nMotorEncoder[right] = 0;
	motor[left] = 00;
	motor[right] = 50;
	}
while(getColorReflected(color) > 15 && getColorReflected(color) < 25)
{
	motor[left] = 25;
	motor[right] = 25;
}
}
}
